### ISSUE TITLE
buttons that are both pressed and hover should have a shadow effect

### ISSUE THREAD

**Issue by qoomBert** [khang-nd/7.css#70] opened 2023-07-12 19:55 UTC
![btnpressed](https://github.com/khang-nd/7.css/assets/139391744/c809e7ed-77f8-4c55-8504-d50cd6190918)
![buttonpressedhovered](https://github.com/khang-nd/7.css/assets/139391744/762cbb82-4de5-48ca-a2b5-b56796d6b689)

**Comment by khang-nd** [comment] 2023-09-01 01:28
Possible duplicate of #20

**Closed** 2023-10-25 12:23 UTC
Labels: enhancement
